import type { Metadata } from "next";

import "./globals.css";
import "../../Webfonts/fontiran.css";
import { ThemeProvider } from "next-themes";
import Header from "@/components/mycomponents/Header";
import Footer from "@/components/mycomponents/Footer";

import { TRPCReactProvider } from "@/trpc/client";
import { getQueryClient, trpc } from "@/trpc/server";

import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
  title: "mobino15",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  const queryClient = getQueryClient();
  void queryClient.prefetchQuery(trpc.categories.getMany.queryOptions());

  return (
    <html dir="rtl" lang="en" suppressHydrationWarning>
      <body className="font-IRANYekanX flex flex-col items-center w-full transition-all">
        <NuqsAdapter>
          <TRPCReactProvider>
            <ThemeProvider enableSystem>
              <Header />

              <div className={cn("w-full bg-[#fcfeff]")}>
                <Toaster />
                {children}
              </div>

              <Footer />
            </ThemeProvider>
          </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
