import type { Metadata } from "next";

import "./globals.css";
import "../../Webfonts/fontiran.css";
import { ThemeProvider } from "next-themes";
import Header from "@/components/mycomponents/Header";
import Footer from "@/components/mycomponents/Footer";

import { TRPCReactProvider } from "@/trpc/client";
import { getQueryClient, HydrateClient, trpc } from "@/trpc/server";
import { Suspense } from "react";
import HeaderSkeleton from "@/components/mycomponents/HeaderSkeleton";

import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "mobino15",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = getQueryClient();
  void queryClient.prefetchQuery(trpc.categories.getMany.queryOptions());

  return (
    <html dir="rtl" lang="en" suppressHydrationWarning>
      <body className="font-IRANYekanX flex flex-col items-center w-full transition-all">
        <TRPCReactProvider>
          <ThemeProvider enableSystem>
            <HydrateClient>
              <Suspense fallback={<HeaderSkeleton />}>
                <Header />
              </Suspense>
              <div className={cn("w-full bg-[#fcfeff]")}>
                <Toaster />
                {children}
              </div>

              <Footer />
            </HydrateClient>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
