/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      subcategories: 'categories';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  label: string;
  /**
   * اعداد کوچکتر در بالای لیست نمایش داده می‌شوند.
   */
  order: number;
  logo?: string | null;
  /**
   * only rgba
   */
  logoColor?: string | null;
  parent?: (string | null) | Category;
  subcategories?: {
    docs?: (string | Category)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  productAddress: string;
  address: string;
  /**
   * اعداد کوچکتر در بالای لیست نمایش داده می‌شوند.
   */
  order: number;
  name: string;
  label: string;
  color:
    | 'TitaniumBlack'
    | 'Black'
    | 'Silver'
    | 'Purple'
    | 'yellow'
    | 'DarkBlue'
    | 'Lemon'
    | 'TitaniumSilver'
    | 'DarkGray'
    | 'NaturalTitanium'
    | 'Golden'
    | 'TitaniumGray'
    | 'TitaniumIceBlue'
    | 'Gray'
    | 'NavyBlue'
    | 'Brick'
    | 'TitaniumDesert'
    | 'TitaniumPurple'
    | 'JetBlackTitanium'
    | 'LightGreen'
    | 'Turquoise'
    | 'LightGray'
    | 'LightBlue'
    | 'Pink'
    | 'TitaniumWhite'
    | 'Green'
    | 'Cream'
    | 'Blue'
    | 'White'
    | 'Red'
    | 'Orange'
    | 'graphite'
    | 'oceanBlue'
    | 'roseGold'
    | 'oliveGreen'
    | 'copper'
    | 'bronze'
    | 'charcoalGray'
    | 'skyBlue'
    | 'lilac'
    | 'mintGreen';
  price: number;
  offPrice?: number | null;
  category: string | Category;
  subCategory: string | Category;
  images?:
    | {
        url: string;
        isMain?: boolean | null;
        id?: string | null;
      }[]
    | null;
  quantity: number;
  seller?: 'mobino' | null;
  introduction: string;
  available?: boolean | null;
  productType?:
    | (
        | {
            brand: 'apple' | 'samsung' | 'xiaomi' | 'huawei' | 'nokia' | 'sony';
            model: string;
            /**
             * دسته بندی گوشی
             */
            classification?: ('Economic' | 'FlagBearer' | 'MidRange') | null;
            ram: '4gb' | '6gb' | '8gb' | '12gb' | '16gb';
            storage: '64gb' | '128gb' | '256gb' | '512gb' | '1tb';
            /**
             * سیستم عامل
             */
            os: 'ios' | 'android' | 'harmony';
            batteryCapacity: number;
            mainCameraResolution: number;
            FrontCameraResolution: number;
            /**
             * نوع پردازنده - CPU
             */
            chipset: string;
            /**
             * تعداد هسته پردازشگر
             */
            cpuCores: '1' | '2' | '4' | '8' | '9' | '10';
            /**
             * پردازنده گرافیکی - GPU :
             */
            gpu: string;
            simCount: '1' | '2';
            dimensions: string;
            weight: number;
            isRegistered?: boolean | null;
            displayType: 'ips' | 'oled' | 'amoled' | 'super_amoled' | 'dynamic_amoled';
            displaySize: string;
            displayResolution: string;
            refreshRate: number;
            network: '2g' | '3g' | '4g' | '5g';
            waterResistant?: boolean | null;
            accessories?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mobile';
          }
        | {
            brand: 'apple' | 'asus' | 'hp' | 'lenovo' | 'msi' | 'dell' | 'acer';
            model: string;
            ram:
              | '2gb'
              | '4gb'
              | '8gb'
              | '12gb'
              | '16gb'
              | '20gb'
              | '28gb'
              | '32gb'
              | '36gb'
              | '40gb'
              | '44gb'
              | '48gb'
              | '64gb'
              | '128gb';
            AbilityToUpgradeLaptopRAM?: boolean | null;
            storages: {
              type: 'ssd' | 'hdd';
              capacity: '64gb' | '128gb' | '256gb' | '512gb' | '1tb' | '2tb' | '4tb';
              id?: string | null;
            }[];
            AbilityToUpgradeLaptopStorage?: boolean | null;
            usage: 'صنعتی' | 'حرفه ای' | 'مالتی مدیا' | 'دسکتاپ' | 'طراحی' | 'عمومی' | 'گیمینگ';
            cpuSeries:
              | 'intel_i3'
              | 'intel_i5'
              | 'intel_i7'
              | 'intel_i9'
              | 'intel_pentium'
              | 'intel_celeron'
              | 'intel_xeon'
              | 'amd_ryzen3'
              | 'amd_ryzen5'
              | 'amd_ryzen7'
              | 'amd_ryzen9'
              | 'amd_athlon'
              | 'amd_fx'
              | 'apple_m1'
              | 'apple_m2'
              | 'apple_m3'
              | 'other';
            CPUProcessorGeneration: '10' | '11' | '12' | '13' | '14';
            gpuInfo: {
              series:
                | 'nvidia_mx'
                | 'nvidia_gtx'
                | 'nvidia_rtx'
                | 'nvidia_quadro'
                | 'amd_rx'
                | 'amd_vega'
                | 'amd_pro'
                | 'intel_iris_xe'
                | 'intel_uhd'
                | 'apple_m_series_gpu'
                | 'other';
              model: string;
            };
            DisplaySize?: number | null;
            screenResolution:
              | 'hd1366x768'
              | 'fullHd1920x1080'
              | 'qhd2560x1440'
              | 'wqhd2560x1600'
              | 'threeK2880x1620'
              | 'retina2880x1800'
              | 'uhd4k3840x2160'
              | 'wuxga1920x1200'
              | 'wxga1280x800'
              | 'qhdPlus3200x1800'
              | 'fiveK5120x2880'
              | 'sixK6016x3384';
            accessories: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'laptop';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  label?: T;
  order?: T;
  logo?: T;
  logoColor?: T;
  parent?: T;
  subcategories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  productAddress?: T;
  address?: T;
  order?: T;
  name?: T;
  label?: T;
  color?: T;
  price?: T;
  offPrice?: T;
  category?: T;
  subCategory?: T;
  images?:
    | T
    | {
        url?: T;
        isMain?: T;
        id?: T;
      };
  quantity?: T;
  seller?: T;
  introduction?: T;
  available?: T;
  productType?:
    | T
    | {
        mobile?:
          | T
          | {
              brand?: T;
              model?: T;
              classification?: T;
              ram?: T;
              storage?: T;
              os?: T;
              batteryCapacity?: T;
              mainCameraResolution?: T;
              FrontCameraResolution?: T;
              chipset?: T;
              cpuCores?: T;
              gpu?: T;
              simCount?: T;
              dimensions?: T;
              weight?: T;
              isRegistered?: T;
              displayType?: T;
              displaySize?: T;
              displayResolution?: T;
              refreshRate?: T;
              network?: T;
              waterResistant?: T;
              accessories?: T;
              id?: T;
              blockName?: T;
            };
        laptop?:
          | T
          | {
              brand?: T;
              model?: T;
              ram?: T;
              AbilityToUpgradeLaptopRAM?: T;
              storages?:
                | T
                | {
                    type?: T;
                    capacity?: T;
                    id?: T;
                  };
              AbilityToUpgradeLaptopStorage?: T;
              usage?: T;
              cpuSeries?: T;
              CPUProcessorGeneration?: T;
              gpuInfo?:
                | T
                | {
                    series?: T;
                    model?: T;
                  };
              DisplaySize?: T;
              screenResolution?: T;
              accessories?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}