import type { Metadata } from "next";

import "./globals.css";
import "./Webfonts/fontiran.css";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="en" suppressHydrationWarning>
      <body className="font-IRANYekanX">
        <ThemeProvider enableSystem>{children}</ThemeProvider>
      </body>
    </html>
  );
}
